#!/hint/bash

#########################################################################
# REPOSITORY CONFIGURATION
#########################################################################
#
repo='https://github.com/archlinux/svntogit-community.git'
repo_name='svntogit-community'

#########################################################################
# SCRIPT SETTINGS
#########################################################################
#
work_dir="$HOME/$repo_name"
log_dir="$work_dir"
makepkg_params=('-fcd' '--skippgpcheck' '--nocheck')
cleanup=1
pkg_target_dir="$HOME/target-svntogit-community"
pkg_pattern='*.pkg.tar.zst'
# -- Duration after which timeout quits makepkg process
# This is to allow the buildbot to continue running even if
# the makepkg process freezes
timeout_after='4h'
# -- Exclude packages containing these strings
exclude=('staging' 'testing' 'i686' 'i386' 'trunk' 'unstable')
