#!/hint/bash
#
# /etc/buildbot.conf
#

#########################################################################
# REPOSITORY CONFIGURATION
#########################################################################
#
repo='https://github.com/archlinux/svntogit-packages.git'
repo_dir='svntogit-packages'

#########################################################################
# SCRIPT SETTINGS
#########################################################################
#
log_dir="$HOME/.local/state/buildbot"
makepkg_params=('-fcd' '--skippgpcheck')
cleanup=1
pkg_target_dir="$HOME/build-target"
pkg_pattern='*.pkg.tar.zst'

#########################################################################
# SCRIPT OVERRIDES
#########################################################################
#
# -- Optional work_dir override
#work_dir='/home/user'
exlude=('java')
